language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./BleachHack-Fabric-1.14/gradlew build --scan -s
  - ./BleachHack-Fabric-1.15/gradlew build --scan -s
  - ./BleachHack-Fabric-1.16/gradlew build --scan -s