language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - bash BleachHack-Fabric-1.14/gradlew clean build
  - bash BleachHack-Fabric-1.15/gradlew clean build
  - bash BleachHack-Fabric-1.16/gradlew clean build