trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd BleachHack-Fabric
      gradlew build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './BleachHack-Fabric/build/libs/bleachhack-6.9.jar'
    ArtifactName: 'BleachHack'
    publishLocation: 'Container'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      urlVer = open("urlVer.xml","w+")
      num = int(3843969) + int($(Build.BuildId))
      
      urlVer.write("<?xml version="1.0" encoding="UTF-8"?>\n\n<file>\n\n<urlVer>" + str(num) + "</urlVer>\n\n</file>")
      
      urlVer.close()

- task: SetValueFromXML@0
  inputs:
    variableName: 'urlVersion'
    xPathExpression: '@*'
    namespaces: 'urlVer = urlVer'
    xmlFile: './urlVer.xml'

- task: ado-discord-webhook@1
  inputs:
    channelId: '$(webhookChannel)'
    webhookKey: '$(webhookKeyBoi)'
    name: 'Build Poster 2: Electric Boogaloo'
    messageType: 'content'
    content: 'Download (sign in to MS account): https://dev.azure.com/dragoclanleader/_apis/resources/Containers/$(urlVersion.urlVer)?itemPath=BleachHack$(Build.BuildId)&$format=zip'