trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd BleachHack-Fabric
      gradlew build

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'BleachHack'
    repositoryName: 'd1gress/bleachhack-1.14'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'B$(Build.BuildId)'
    title: 'BleachHack b$(Build.BuildId)'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'beta build'
    assets: './BleachHack-Fabric/build/libs/bleachhack-6.9.jar'
    isPreRelease: true
    changeLogCompareToRelease: 'lastNonDraftRelease'
    changeLogType: 'commitBased'