trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd BleachHack-Fabric
      gradlew build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './BleachHack-Fabric/build/libs/bleachhack-6.9.jar'
    ArtifactName: 'BleachHack$(Build.BuildId)'
    publishLocation: 'Container'

- task: ado-discord-webhook@1
  inputs:
    channelId: '$(webhookChannel)'
    webhookKey: '$(webhookKeyBoi)'
    name: 'Build Poster'
    messageType: 'embeds'
    embeds: |
      [{
          "title": "New build from Pipelines.",
          "description": "https://dev.azure.com/dragoclanleader/_apis/resources/Containers/$(urlVer)?itemPath=BleachHack80&$format=zip",
          "author": "Qther's Pipeline Webhook"
      }]