trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd BleachHack-Fabric
      gradlew build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './BleachHack-Fabric/build/libs/bleachhack-6.9.jar'
    ArtifactName: 'BleachHack$(Build.BuildId)'
    publishLocation: 'Container'

- task: ado-discord-webhook@1
  inputs:
    channelId: '$(webhookChannel)'
    webhookKey: '$(webhookKeyBoi)'
    name: 'Build Poster 2: Electric Boogaloo'
    messageType: 'content'
    content: 'Download (sign in to MS account): https://dev.azure.com/dragoclanleader/_apis/resources/Containers/$(UrlVer)?itemPath=BleachHack$(Build.BuildId)&$format=zip'